import { useId, useState } from 'react'
import type { PortalClosing, PortalCustomerDetail, PortalCustomers, PortalDashboard, PortalGoals, PortalPage, PortalPermissions, PortalPpp, PortalRanking, PortalSale, PortalTrades } from './portalTypes'
import { Empty, Metric, Resource, SalesList } from './PortalShared'
import { currentMonth, date, dateTime, filterQuery, money, monthFilters, number, percent } from './portalFormatting'
import { apiRequest } from '../../api/client'

function DailyRevenueChart({ days }: { days: PortalDashboard['dailyTrend'] }) {
  const titleId = useId()
  const minimum = Math.min(0, ...days.map(day => day.netRevenue))
  const maximum = Math.max(0, ...days.map(day => day.netRevenue))
  const spread = maximum - minimum || 1
  const x = (index: number) => 24 + index * 592 / Math.max(1, days.length - 1)
  const y = (value: number) => 150 - (value - minimum) * 110 / spread
  return <figure className="portal-daily-chart"><svg viewBox="0 0 640 190" role="img" aria-labelledby={titleId}><title id={titleId}>Receita líquida diária</title><line x1="24" x2="616" y1={y(0)} y2={y(0)} className="portal-chart-baseline" /><polyline points={days.map((day, index) => `${x(index)},${y(day.netRevenue)}`).join(' ')} className="portal-chart-line" />{days.map((day, index) => <circle key={day.date} cx={x(index)} cy={y(day.netRevenue)} r="4" className="portal-chart-dot" tabIndex={0}><title>{date(day.date)}: {money(day.netRevenue)}</title></circle>)}<text x="24" y="180">{date(days[0]?.date)}</text><text x="616" y="180" textAnchor="end">{date(days.at(-1)?.date)}</text></svg><figcaption>Receita líquida por dia. Consulte os valores exatos na tabela abaixo.</figcaption></figure>
}

export function HomeMonthly({ token, base, permissions }: { token: string; base: string; permissions: PortalPermissions | null | undefined }) {
  const month = currentMonth()
  const showMoney = permissions?.canViewCommission || permissions?.canViewPrize
  return <section className="portal-monthly"><h2>Seu mês em foco</h2><p className="portal-help">{month.split('-').reverse().join('/')} · Indicadores mensais e prêmios sujeitos ao fechamento oficial.</p><div className="portal-home-grid">
    {showMoney && <Resource<PortalClosing> token={token} path={`${base}/${permissions?.canViewCommission ? 'commission' : 'closings'}?month=${month}`}>{data => <section className="portal-panel">{permissions?.canViewCommission && <Metric primary label={data.isEstimated ? 'Comissão estimada' : 'Comissão oficial'} value={money(data.commission)} />}{permissions?.canViewPrize && data.totalAwards != null && <Metric label={data.isEstimated ? 'Prêmios estimados' : 'Prêmios oficiais'} value={money(data.totalAwards)} />}</section>}</Resource>}
    {permissions?.canViewPPP && <Resource<PortalPpp> token={token} path={`${base}/ppp?month=${month}`}>{data => <section className="portal-panel"><h3>PPP do mês</h3>{data.achievementPercent != null ? <><Metric label="Atingimento PPP" value={percent(data.achievementPercent)} />{permissions.canViewPrize && data.award != null && <p className="portal-help">{data.isApproved ? 'Prêmio oficial' : 'Prêmio estimado'}: {money(data.award)}</p>}</> : <Empty>{data.unavailableReason ?? 'PPP ainda não disponível.'}</Empty>}</section>}</Resource>}
    {permissions?.canViewTrades && permissions.canViewRevenue && permissions.canViewCustomers && <Resource<PortalTrades> token={token} path={`${base}/trades?${filterQuery(monthFilters(month))}`}>{data => <section className="portal-panel"><h3>Trocas do mês</h3><Metric label="Trocas sobre vendas" value={percent(data.tradeToSalesPercent)} /><p className="portal-help">Trocas físicas: {money(data.physicalTrades)}</p></section>}</Resource>}
    {permissions?.canViewGoals && <Resource<PortalGoals> token={token} path={`${base}/goals?month=${month}`}>{data => <section className="portal-panel"><h3>Metas do mês</h3>{data.items?.length ? <div className="portal-list">{data.items.slice(0, 4).map((goal, index) => <div className="portal-record" key={`${goal.brand}-${goal.type}-${index}`}><div className="portal-record-top"><strong>{goal.brand}</strong><span>{percent(goal.achievedPercent)}</span></div><small>{goal.type === 'FATURAMENTO' ? 'Faturamento' : 'Positivação'}{permissions.canViewPrize && goal.currentPrize != null ? ` · Prêmio ${data.isApproved ? 'oficial' : 'estimado'} ${money(goal.currentPrize)}` : ''}</small></div>)}</div> : <Empty>{data.unavailableReason ?? 'Metas ainda não disponíveis.'}</Empty>}</section>}</Resource>}
  </div>{!showMoney && !permissions?.canViewPPP && !permissions?.canViewGoals && <p className="portal-help">Seu perfil não possui outros indicadores mensais autorizados.</p>}</section>
}

export function PersonalDashboard({ data }: { data: PortalDashboard }) {
  return <><div className="portal-kpis"><Metric primary label="Receita líquida do período" value={money(data.period.netRevenue)} hint={`${date(data.startDate)} a ${date(data.endDate)}`} /><Metric label="Vendas brutas" value={money(data.period.grossSales)} /><Metric label="Movimentos negativos" value={money(data.period.negativeMovements)} /><Metric label="Clientes com movimento" value={number(data.period.customerCount)} /></div><section className="portal-panel portal-rhythm"><h2>Seu ritmo de vendas</h2><div className="portal-kpis portal-kpis-small"><Metric label="Hoje" value={money(data.today.netRevenue)} hint={date(data.referenceDate)} /><Metric label="Mês atual" value={money(data.month.netRevenue)} /><Metric label="Documentos no período" value={number(data.period.documentCount)} /><Metric label="Ticket líquido por documento" value={money(data.period.averageTicket)} /></div>{data.period.movementCount === 0 ? <Empty>Nenhum movimento no período selecionado.</Empty> : data.dailyTrend.length > 0 && <><DailyRevenueChart days={data.dailyTrend} /><details className="portal-daily-table"><summary>Ver valores por dia</summary><div className="portal-table-scroll"><table><thead><tr><th>Dia</th><th>Vendas brutas</th><th>Receita líquida</th></tr></thead><tbody>{data.dailyTrend.map(day => <tr key={day.date}><td>{date(day.date)}</td><td>{money(day.grossSales)}</td><td>{money(day.netRevenue)}</td></tr>)}</tbody></table></div></details></>}</section><p className="portal-source">Fonte: {data.freshness.source === 'csv' ? 'Arquivo CSV importado' : data.freshness.source === 'firebird' ? 'Firebird' : 'Não disponível'} · {data.freshness.updatedAtUtc ? `${data.freshness.timestampKind === 'import-started' ? 'Importação iniciada' : 'Sincronização concluída'} em ${dateTime(data.freshness.updatedAtUtc)}` : 'Data de atualização não disponível'}.</p></>
}
export function Sales({ data, onPage }: { data: PortalPage<PortalSale>; onPage: (page: number) => void }) {
  return <>{data.items.length ? <SalesList items={data.items} /> : <Empty>Nenhuma venda no período selecionado.</Empty>}<div className="portal-pagination"><button disabled={data.page <= 1} onClick={() => onPage(data.page - 1)} aria-label="Página anterior"><i className="fa-solid fa-arrow-left" aria-hidden="true" /></button><span>Página {data.page} · {number(data.totalCount)} movimentos</span><button disabled={data.page * data.pageSize >= data.totalCount} onClick={() => onPage(data.page + 1)} aria-label="Próxima página"><i className="fa-solid fa-arrow-right" aria-hidden="true" /></button></div></>
}
export function Customers({ data, onSelect }: { data: PortalCustomers; onSelect: (code: string) => void }) {
  return <><p className="portal-help">Clientes observados nas suas compras do período. Esta lista não representa a carteira completa do ERP.</p>{data.items.length ? <div className="portal-list">{data.items.map(customer => <button className="portal-record portal-customer" key={customer.customerCode} onClick={() => onSelect(customer.customerCode)}><div className="portal-record-top"><strong>{customer.customerCode && `${customer.customerCode} · `}{customer.customerName}</strong><span>{money(customer.netRevenue)}</span></div><div className="portal-record-meta"><span>{customer.city}</span><span>Última compra: {date(customer.lastPurchaseDate)}</span></div></button>)}</div> : <Empty>Nenhum cliente com compra no período selecionado.</Empty>}{data.hasMore && <p className="portal-help">Exibindo os primeiros {data.items.length} de {number(data.totalCount)} clientes. Refine os filtros.</p>}</>
}
export function CustomerDetail({ data }: { data: PortalCustomerDetail }) {
  const days = new Map<string, PortalSale[]>()
  for (const sale of data.sales) {
    const day = sale.date.slice(0, 10)
    const products = days.get(day) ?? []
    products.push(sale)
    days.set(day, products)
  }
  const orderedDays = [...days.entries()].sort(([left], [right]) => right.localeCompare(left))
  return <>
    <h2 className="portal-customer-title">{data.customer.customerCode && `${data.customer.customerCode} · `}{data.customer.customerName}</h2>
    <p className="portal-help">{data.customer.city}</p>
    <div className="portal-kpis"><Metric primary label="Receita líquida" value={money(data.customer.netRevenue)} /><Metric label="Documentos" value={number(data.customer.documentCount)} /><Metric label="Ticket líquido por documento" value={money(data.customer.averageTicket)} /><Metric label="Quantidade comprada" value={number(data.customer.purchasedQuantity)} /></div>
    <h2>Produtos por dia</h2>
    {orderedDays.length ? <div className="portal-customer-days">{orderedDays.map(([day, products]) => <section className="portal-customer-day" key={day} aria-label={`Produtos de ${date(day)}`}>
      <header className="portal-customer-day-heading"><h3><time dateTime={day}>{date(day)}</time></h3><span>{number(products.length)} {products.length === 1 ? 'movimento exibido' : 'movimentos exibidos'}</span></header>
      <ul className="portal-customer-products">{products.map(sale => <li className="portal-customer-product" key={sale.id}>
        <div className="portal-customer-product-name"><strong>{sale.productName}</strong><span>{sale.brand} · Doc. {sale.documentNumber}</span></div>
        <div className="portal-customer-product-quantity"><span>Quantidade</span><strong>{number(sale.quantity)} un.</strong></div>
        <div className="portal-customer-product-type"><span>Tipo</span><strong>{sale.movementType}</strong></div>
        <div className="portal-customer-product-value"><span>Valor</span><strong>{money(sale.totalValue)}</strong></div>
      </li>)}</ul>
    </section>)}</div> : <Empty>Nenhum produto no período selecionado.</Empty>}
    {data.hasMore && <p className="portal-help">Lista limitada. Refine o período para ver outros movimentos.</p>}
  </>
}
export function Ranking({ data }: { data: PortalRanking }) { return <>{data.items.length ? <div className="portal-list">{data.items.map(item => <article className="portal-record" key={item.label}><div className="portal-record-top"><strong>{item.label}</strong><span>{money(item.netRevenue)}</span></div><div className="portal-record-meta"><span>{number(item.quantity)} unidades · {number(item.customerCount)} clientes</span><span>{percent(item.revenueSharePercent)} da receita líquida</span></div></article>)}</div> : <Empty>Nenhum resultado no período selecionado.</Empty>}{data.hasMore && <p className="portal-help">Exibindo os primeiros {data.items.length} de {number(data.totalCount)} resultados. Refine os filtros.</p>}</> }
export function Goals({ data }: { data: PortalGoals }) {
  if (!data.items.length) return <Empty>{data.unavailableReason ?? 'Metas não disponíveis para este mês.'}</Empty>
  return <>{!data.available && <p className="portal-message" role="status">{data.unavailableReason ?? 'Prêmios não disponíveis para este mês.'}</p>}{data.items.length ? <div className="portal-goals">{data.items.map((goal, index) => <article className="portal-panel" key={`${goal.brand}-${goal.type}-${index}`}><div className="portal-record-top"><h2>{goal.brand}</h2><span>{goal.type === 'FATURAMENTO' ? 'Faturamento' : goal.type === 'POSITIVACAO' ? 'Positivação' : goal.type}</span></div><strong className="portal-goal-value">{percent(goal.achievedPercent)}</strong>{goal.achievedPercent != null && <progress max="100" value={goal.achievedPercent} aria-label={`Meta ${goal.brand} ${goal.type}`} />}<dl className="portal-values"><div><dt>Realizado</dt><dd>{goal.type === 'FATURAMENTO' ? money(goal.actual) : number(goal.actual)}</dd></div><div><dt>Meta</dt><dd>{goal.type === 'FATURAMENTO' ? money(goal.target) : number(goal.target)}</dd></div>{goal.currentPrize != null && <div><dt>{data.isApproved ? 'Prêmio oficial' : 'Prêmio estimado'}</dt><dd>{money(goal.currentPrize)}</dd></div>}{goal.nextTierPercent != null && <><div><dt>Próxima faixa</dt><dd>{percent(goal.nextTierPercent)}</dd></div><div><dt>Falta para a faixa</dt><dd>{goal.type === 'FATURAMENTO' ? money(goal.amountToNextTier) : number(goal.amountToNextTier)}</dd></div>{goal.nextTierPrize != null && <div><dt>Prêmio na próxima faixa</dt><dd>{money(goal.nextTierPrize)}</dd></div>}</>}</dl></article>)}</div> : <Empty>Nenhuma meta cadastrada para este mês.</Empty>}<p className="portal-help">{data.isApproved ? 'Prêmios oficiais do fechamento aprovado. Valores congelados.' : 'Prêmios são estimativas até a aprovação do fechamento mensal.'}</p></>
}
export function Ppp({ data }: { data: PortalPpp }) { return !data.segments.length && data.achievementPercent == null ? <Empty>{data.unavailableReason ?? 'PPP não disponível para este mês.'}</Empty> : <>{!data.available && <p className="portal-message" role="status">{data.unavailableReason ?? 'Prêmio não disponível para este mês.'}</p>}<div className="portal-kpis"><Metric primary label="Atingimento PPP" value={percent(data.achievementPercent)} />{data.award != null && <Metric label={data.isApproved ? 'Prêmio PPP oficial' : 'Prêmio PPP estimado'} value={money(data.award)} />}</div><div className="portal-list">{data.segments.map(segment => <article className="portal-record" key={segment.segment}><div className="portal-record-top"><strong>{segment.segment}</strong><span>{percent(segment.achievementPercent)}</span></div><p>{number(segment.customerCount)} clientes · {number(segment.groupsPlaced)} grupos positivados · {number(segment.itemsPerSegment)} itens por segmento</p></article>)}</div></> }
export function Trades({ data }: { data: PortalTrades }) { return <><div className="portal-kpis"><Metric primary label="Trocas físicas" value={money(data.physicalTrades)} /><Metric label="Trocas sobre vendas" value={percent(data.tradeToSalesPercent)} /><Metric label="Movimentos" value={number(data.movementCount)} /></div>{data.items.length ? <SalesList items={data.items} /> : <Empty>Nenhuma troca no período selecionado.</Empty>}{data.hasMore && <p className="portal-help">Lista limitada. Refine os filtros para consultar outros movimentos.</p>}</> }
const closingStatus = { EmApuracao: 'Em apuração', EmConferencia: 'Em conferência', Aprovado: 'Aprovado' }
export function Closing({ data, commissionOnly = false, token, base, month, canApprove, onChanged }: { data: PortalClosing; commissionOnly?: boolean; token: string; base: string; month: string; canApprove: boolean; onChanged: () => void }) {
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  async function transition(action: string) {
    setBusy(true); setError('')
    try { await apiRequest(`${base}/closings/${action}?month=${month}`, token, { method: 'POST' }); onChanged() }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível atualizar o fechamento.') }
    finally { setBusy(false) }
  }
  const values: Array<[string, number | null, boolean?]> = commissionOnly ? [['Base de comissão', data.commissionableRevenue], ['Percentual de comissão', data.commissionPercent, true], ['Comissão', data.commission]] : [['Receita', data.revenue], ['Base de comissão', data.commissionableRevenue], ['Comissão', data.commission], ['Atingimento PPP', data.pppPercent, true], ['Prêmio PPP', data.pppAward], ['Prêmio faturamento', data.revenueAward], ['Prêmio positivação', data.positivityAward], ['Prêmio trocas', data.tradeAward], ['Total de prêmios', data.totalAwards], ['Trocas', data.tradeValue], ['Percentual de trocas', data.tradePercent, true]]
  return <section className="portal-panel"><div className="portal-record-top"><h2>{commissionOnly ? 'Sua comissão' : 'Resultado do mês'}</h2><span className={`portal-badge ${data.status === 'Aprovado' ? 'approved' : ''}`}>{closingStatus[data.status]}</span></div><p className="portal-help">{data.isEstimated ? 'Valores estimados, sujeitos à conferência e aprovação.' : `Fechamento oficial aprovado em ${date(data.approvedAtUtc)}. Valores congelados.`}</p>{!commissionOnly && data.commissionAndAwards != null && <Metric primary label="Comissão e prêmios" value={money(data.commissionAndAwards)} />}<dl className="portal-values">{values.filter(([, value]) => value != null).map(([label, value, ratio]) => <div key={label}><dt>{label}</dt><dd>{ratio ? percent(value) : money(value)}</dd></div>)}</dl>{canApprove && !commissionOnly && data.status !== 'Aprovado' && <div className="portal-actions">{data.status === 'EmApuracao' && <button disabled={busy} onClick={() => void transition('review')}>Iniciar conferência</button>}{data.status === 'EmConferencia' && <button disabled={busy} onClick={() => void transition('approve')}>Aprovar fechamento</button>}<small>A aprovação congela os valores deste mês.</small></div>}{error && <p role="alert" className="portal-message">{error}</p>}</section>
}
export function ClosingHistory({ token, base, onSelect }: { token: string; base: string; onSelect: (month: string) => void }) { return <section className="portal-panel"><h2>Histórico de fechamentos</h2><Resource<Array<{ month: string; status: keyof typeof closingStatus }>> token={token} path={`${base}/closings/history`}>{history => history.length ? <div className="portal-list">{history.map(item => <button className="portal-record portal-record-top" key={item.month} onClick={() => onSelect(item.month)}><strong>{item.month.split('-').reverse().join('/')}</strong><span>{closingStatus[item.status]}</span></button>)}</div> : <Empty>Nenhum mês disponível no histórico.</Empty>}</Resource></section> }
